name: test

on:
  issue_comment:
    types:
      - created

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        path: main
    - uses: actions/setup-ruby@v1
      with:
        ruby-version: '2.7'
    - name: hoge
      env:
        GENV: ${{ toJson(env) }}
        REPO: ${{ github.repository }}
      run: |
        echo $REPO
        echo $GENV
    - name: ここでbranch名とrevision情報の取得
      env:
        PR_URL: ${{ github.event.issue.pull_request.url }}
        TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        ruby $GITHUB_WORKSPACE/.github/workflows/pr-getter.rb
        echo "Set branch name and branch head sha to env"
    - name: check
      run: |
        echo $branch_name
        echo $sha
    - uses: actions/checkout@v2
      with:
        repository: thinceller/dotfiles
        path: dotfiles
    - name: hoge
      env:
        GENV: ${{ toJson(env) }}
        REPO: ${{ github.repository }}
      run: |
        echo $REPO
        echo $GENV
